### ISSUE TITLE
Add support for multiple deployment files

### ISSUE THREAD

**Issue by rodcloutier** [jelmansouri/setupscripts#10]
We should probably support multiple deployment files.
This would allow components to specify deployment files to be used in their context and allow user to specify addidtional deployment for their own usage.

Usage could be:
`Deployer.exe the_project.yaml my_stuff.yaml`

We should probably resolve the duplicates somehow (maybe not allow them, or use a last defined override rule). 

Clean-up can only would need to only be done once all the files are processed.

**Comment by jelmansouri** [comment]
Was thinking about it yesterday too, but I wanted it primarily for overrides following a last override rule.
I'll work on it soon. Want to add Nuget Packages support tonight first.

**Comment by jelmansouri** [comment]
I commited preliminary support, note that I removed default deployment file support, at this point with json and yml support it doesn't make sens anymore.
Currenly having two same toolset in two different deployment files is gonna throw an exception, I'm gonna close the ticket one I implement that logic.

**Comment by jelmansouri** [comment]
FYI, if you plan to do bigger changes note that I'm refactoring the Deployer. Halfway done will push something by tomorrow.

**Comment by jelmansouri** [comment]
fixed with https://github.com/jelmansouri/setupscripts/commit/f78650640ffbd96ed64b1b690db201020df21f02
